### ISSUE TITLE
M2E archetype has changed it structure

### ISSUE THREAD

**Issue by HannesWell** [eclipse-scout/scout.sdk#23]
At m2e we changed the structure of the o.e.m2e.archetype.common Plugin from a Plugin that embeds the archetype jars to multiple fragment bundles that are fetched directly from Maven-Central and wrapped to OSGi bundles by M2E's Maven Target Location:
- https://github.com/eclipse-m2e/m2e-core/pull/1411
- https://github.com/eclipse-m2e/m2e-core/pull/1494

I noticed that you are using the m2e.archetype bundle explicitly so I wanted to make you aware of that.

**Comment by fschinkel** [comment]
@HannesWell thanks for the notification. The dependency was an old one and the archetype-bundle was no longer used, so i removed the dependency (see #25).
