### ISSUE TITLE
NLS editor broken in IntelliJ plugin for Scout 23.2.9

### ISSUE THREAD

**Issue by rabanti-github** [eclipse-scout/scout.sdk#26]
## Description
The IntelliJ plugin for the Eclipse Scout framework (Java) seems to have a broken NLS editor for the most recent Scout version (23.2.9). Special characters like German Umlauts are not escaped anymore in the corresponding properties files. Instead of the expected `Hinzuf\u00F6gen` (Hinzufügen), the properties file contains `Hinzuf?gen` and the NLS editor shows `Hinzuf�gen`. In an external editor (like Notepad++), the term is displayed correctly, if set to ANSI.
Furthermore, If the term is fixed in the NLS editor within IntelliJ, the updated special characters are displayed correctly first, but as soon as the NLS editor is re-opened, the wrong “?” characters are shown again. Sometimes, there is also a message, indicating that the translation has changed outside of the editor even nothing was changed. After reloading, all changed special characters are again in the wrong state. The translated string is also wrong displayed in the frontend when the application is started and viewed in a browser.

## Environment
| Property | Value | Notes |
| --- | --- | --- |
| OS | WIN10 PRO x64 21H2||
| OS language | German (Swiss) ||
| IntelliJ | 2023.2.3 Community| Build #IC-232.10072.27, built on October 11, 2023 |
| Scout plugin | 13.0.0.231941301||
| Java | Azul Zulu 17.0.2||
| Scout version (broken) | 23.2.9||
| Scout version (working) | 22.0.41 | Versions between 22.0.41 and 23.2.9 were not tested|
| Versioning | No versioning system like git was used in the test projects | no influence due to VCS|
| Cloud systems | No cloud systems like OneDrive was used to synchronize files in the test projects |no influence due to file synchronization|

## How to reproduce
1.	Create a new Scout project in IntelliJ: File &rarr; New &rarr; Project &rarr; Scout
2.	Fill I in the project information and select version 23.2.9 (for Java)
3.	Complete the setup, using the “Create” button
4.	Complete setup tasks like building or `npm run pnpm-install`
5.	Go to a Form or TablePage
6.	Edit or create field
7.	Add or change the label (getConfiguredLabel) of the filed, using the return value TEXTS.get(“Add”);
8.	Type the default value (English) “Add” and translation value (German or other) “Hinzufügen”
9.	Change to the NLS editor (_[PROJECT]_.ui.html.app.dev)
10.	In the German (or other) column, the value “Hinzuf?gen” will be shown for “Add”
11.	Try to change the value to “Hinzufügen” (it is assumed that this will trigger the escaping of special characters)
12.	Close the NLS editor
13.	Re-open the NLS editor
14.	The value is back on “Hinzuf?gen”

In UI:
15.	Start the application, using the run command `[webapp] all`
16.	Go the application page at http://localhost:8082/ and into the Form or table page that contains the translated string
17.	The translated sting contains “?” instead of the special character if the language of the browser matches to the corresponding foreign language

## Screenshots
NLS editor
![image](https://github.com/eclipse-scout/scout.sdk/assets/6697127/7f9b7445-68ee-48b4-9591-05d4ef183edf)

Notification about external change
![image](https://github.com/eclipse-scout/scout.sdk/assets/6697127/1760e1f9-0ae8-4586-b3f0-651bd475c121)

rendered frontend page
![image](https://github.com/eclipse-scout/scout.sdk/assets/6697127/eed9dc37-f651-43e1-9b1e-1bfd9cdde3e6)

**Comment by cguglielmo** [comment]
Hi,

Scout now expects the *.properties files to use UTF-8 encoding, so you need to convert your files, see https://eclipsescout.github.io/scout-docs/23.2/migration/migration-guide.html#properties-files-using-utf-8-instead-of-iso-8859-1-latin-1 .

Obviously, a newly created project incorrectly uses the encoding ISO-8859-1 instead of UTF-8, this needs to be fixed. Thank you for reporting it!

**Comment by mvilliger** [comment]
Hi

Thanks for pointing that out. A new plugin is available that should fix this issue.
Can you please update and confirm?

**Comment by rabanti-github** [comment]
Hello,
I tested the updated version with a new Scout Project. Looks good and works as expected.
After converting the properties files to UTF-8 also the old projects worked as expected.
I have just one last question about the documentation.
In the migration guide it is stated:
```
Existing files need to be converted, e.g. by the help of native2ascii, which is available up to (but not including) JDK 17. Execute the following command in your workspace directory:

find . -name "*.properties" -exec native2ascii -reverse -encoding utf8 {} {} \;
```
However, I don't know exactly what tis means. Is this applicable to CMD (Windows), bash (Linux)? Also, I have not found an binary native2ascii in my Java11 environment (also not in Java17, as described). Is this supposed to be part of OpenJDK or is this something Oracle specific? May it be that this tool was even deprecated before Java11?

Thank you in advance, and thank you very much for the fix

**Comment by mvilliger** [comment]
Hi

Thanks for testing. I am happy it works now!

As far as I can see this script is for a Linux bash. You should therefore be able to execute it e.g. in WSL if you are working on Windows. Maybe environments like Cygwin or similar could work too (untested).

The native2ascii tool is at least part of the [Adoptium OpenJDK 8](https://adoptium.net/temurin/releases/?version=8&package=jdk). Don't know about other versions or JDKs.
I will clarify that in the migration guide accordingly.

As an alternative to the native2ascii script you can also use the NLS Editor of the IDE to convert the files. It should be able to load the old (encoded) properties files and will write the new (un-encoded) ones when changing a text. This may only be handy if you only have a few properties files (you may have to change a property in every language to convert every file).

Hope this helps

**Comment by rabanti-github** [comment]
Thank you for the clarification.
I have looked into my Java distribution (Azul). native2ascii was part there in Zulu OpenJDK8 but seems to be removed in Zulu OpenJDK11. Furthermore, Oracle states the removal in Java 9 here: https://docs.oracle.com/en/java/javase/11/migrate/index.html#GUID-4DD638C3-E565-42B6-AA32-00AFC16930AB
Therefore, the documentation would probably be more informative, like this:
```
Existing files need to be converted, e.g. by the help of native2ascii, which is available up to JDK 8. Execute the following command in your workspace directory:
find . -name "*.properties" -exec native2ascii -reverse -encoding utf8 {} {} \;

If native2ascii is not available, a manual conversion of the text properties files from ISO-8859-1 to UTF-8, using an editor like Emacs, Vim, Visual Studio Code or Notepad++, is also possible. The files are located in the resource folder of the shared project (e.g. helloscout.shared\src\main\resources\org\eclipse\scout\apps\helloscout\shared\texts\Texts.properties)
```

**Comment by mvilliger** [comment]
Ok, thanks for the check.
